version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html/app
      - ./config:/var/www/html/config
      - ./database:/var/www/html/database
      - ./routes:/var/www/html/routes
      - ./resources:/var/www/html/resources
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'nano_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql
